### ISSUE TITLE
Usage with Java projects

### ISSUE THREAD

**Issue by Ramanpreetsingh** [beryx/handlebars-java-helpers#1]
I have added the maven dependancy in my java spring boot project. But while invoking the helper, it's giving me "could not find helper" error. Do I need to register the helpers or do anything else to use them?

**Comment by siordache** [comment]
Yes, you need to register the helpers:
```
Handlebars handlebars = ...
org.beryx.hbs.Helpers.register(handlebars);
```

**Comment by Ramanpreetsingh** [comment]
Thanks, it is working now. 

Side note to others, to run this :  download the groovy-all.jar and add it to the classpath.
With Maven, add this to your dependencies :
```
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.4.5</version>
</dependency>
```
